version: "3.3"

services:
  rabbitmq:
    image: rabbitmq:3-management
    hostname: rabbitmq
    ports:
      - "15672:15672"
      - "5672:5672"
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "5672"]
      interval: 30s
      timeout: 10s
      retries: 5
    container_name: rabbitmq
    labels:
      NAME: rabbitmq
    volumes:
      - ./enabled_plugins:/etc/rabbitmq/enabled_plugins

  dotnet-api:
    image: dotnet-api-image
    build:
      context: ./Backend
      dockerfile: Dockerfile
    ports:
      - "8081:5001"
    depends_on:
      - rabbitmq

  frontend:
    container_name: frontend
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - dotnet-api
